# Experiment: check can update wiki with version.
# [Syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)
# [Triggers](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#about-events-that-trigger-workflows)
# [Variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)
# [Actions](https://github.com/marketplace?type=actions)
name: experiment

on:
  push:
    tags:
    - "x*"
    
jobs:
  prep:
    runs-on: ubuntu-latest
    name: "Update Wiki doc"
    steps:
    - uses: actions/checkout@v3
    
    - name: ver
      id: ver
      shell: pwsh
      run: |
        $version = "${{github.ref_name}}".Substring(1);
        
        write-output "PackageVersion=$version" >> $env:GITHUB_OUTPUT
      
    - name: updatewiki
      run: |
        $version = '${{steps.ver.outputs.PackageVersion}}'
        write-host "Package Version - '$version'"
        . update-wiki.ps1 -PackageVersion $version
      shell: pwsh

    - name: wiki artifact
      uses: actions/upload-artifact@v3
      with:
        name: wiki
        path: wiki/_Footer.md
        if-no-files-found: error
  