# Tag based release.
# Build and publish to github
# Publish to nuget
# using the provided tag as the version.
#
# Only works on selected branches
#

name: release via tag

on:
  push:
    tags:
      - "v-*"
env:
  PackTarget: src/kwd.CoreUtil
  PackBranches: "master,build,development"

jobs:
  check:
    name: 'check is valid branch'
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{steps.check_branch.outputs.build_version}}
      is_preview: ${{steps.check_branch.outputs.is_preview}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check_branch
        id: check_branch
        shell: pwsh
        run: |
          $tagBranches = "$(git branch -r --contains ${{github.ref}})"
          $allowed = "${{env.PackBranches}}" -split ','
          
          foreach($item in $allowed){
            if($tagBranches.Contains($item)){
              $relVersion = "${{github.ref_name}}".Substring(2);
              
              $isPreview = if($relVersion.Contains("-")){'true'}else{'false'};

              echo build_version=$relVersion >> $env:GITHUB_OUTPUT
              echo is_preview=$isPreview >> $env:GITHUB_OUTPUT
              
              echo "Allow building release - $relVersion"
              echo "Is Preview $isPreview"
              return;
            }
          }
          echo build_version="" >> $env:GITHUB_OUTPUT
          echo Deny
      
      - name: results
        run: |
          echo BuildVersion - ${{steps.check_branch.outputs.build_version}}
          echo IsPreview - ${{steps.check_branch.outputs.is_preview}}
  build:
    runs-on: ubuntu-latest
    name: "Build release package"
    needs: "check"
    if: needs.check.outputs.build_version != ''
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore --locked-mode src/

    - name: Test
      run: dotnet test -c Release --verbosity normal --logger trx --results-directory "TestResults" src/
    
    - name: Pack
      run: >
        dotnet pack 
        -c Release 
        --include-symbols
        ${{env.PackTarget}}
        -p:ContinuousIntegrationBuild=true 
        -p PackageVersion=${{needs.check.outputs.build_version}}
        -o packages
    
    - name: Keep package artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: packages/
        if-no-files-found: error
        
    - name: Push package to github
      run: > 
        dotnet nuget push 
        packages/*.nupkg 
        --source https://nuget.pkg.github.com/dkowald/index.json
        --api-key ${{ secrets.GITHUB_TOKEN }}
        
    - name: Nuget publish
      run: >
        dotnet nuget push
        "packages/*.*"
        --api-key ${{secrets.NUGETPUSH}}
        --source https://api.nuget.org/v3/index.json
        
    
    - name: Clone wiki
      uses: actions/checkout@v3
      with:
       repository: 'https://github.com/Dkowald/kwd.CoreUtil.wiki.git'
       ref: 'build' #todo: swap to master when works.
       path: 'w'

    - name: Publish wiki files
      run: |
       rm -r w/*
       cp -r wiki/* w/
       cd w
       git add -A
       git commit -m "release ${{needs.check.outputs.build_version}}"
       git push
    
    - name: Create release
      uses: ncipollo/release-action@v1      
      with:
        draft: true
        prerelease: ${{needs.check.outputs.is_preview}}
        artifacts: "./packages/*"
   