# Tag based release.
# Build and publish to github
# using the provided tag as the version.
#
# Only works on master and development branches
#
on:
  push:
    #todo: remove, this here to help develop  
    branches:
     - build
    tags:
      - "*"
env:
  PackTarget: src/kwd.CoreUtil
  PackBranches: "master , Development"

jobs:
  check:
    name: 'check is valid branch'
    runs-on: ubuntu-latest
    outputs:
      valid_branch: ${{steps.check_branch.outputs.valid_branch}}
    steps:
      - name: check_branch
        id: check_branch
        shell: pwsh
        run: |
          $tagBranches = "$(git branch --contains ${{github.ref_name}})"
          $allowed = ${{PackBranches}} -split ','
          foreach($item in $allowed){
            if($tagBranches.Contains($item)){
              echo valid_branch=true >> $GITHUB_OUTPUT
              echo Allow
              return;
            }
          }
          echo valid_branch=false >> $GITHUB_OUTPUT
          echo Deny
        
  build:
    runs-on: ubuntu-latest
    name: "Build release package"
    needs: ["check"]
    if: $${{needs.check.valid_branch}}
    steps:
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode src/

    - name: Pack
      run: echo "TODO pack $PackTarget"
      #run: >
      #  dotnet pack 
      #  -c Release 
      #  --include-symbols
      #  $PackTarget
      #  -p:ContinuousIntegrationBuild=true 
      #  -p PackageVersion= ${{github.ref_name}}
      #  -o packages
    
    - name: Publish to github packages
      shell: pwsh  
      run: echo "TODO"
      
    
